// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlbkmuwhnwhcfwbdzsiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYmttdXdobndoY2Z3YmR6c2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDA2MTYsImV4cCI6MjA2NDYxNjYxNn0.6asmyNWFl84kIMz9lorWd2dzs19xrneuvOg_VEjdhYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);